---
kind: PersistentVolumeClaim
apiVersion: v1

metadata:
    name: my-pvc
    namespace: myns
    labels:
        name: my-pvc

spec:
    accessModes:
    - ReadWriteOnce
    volumeName: my-pv
    resources:
       requests:
          storage: 2Gi

