---
apiVersion: v1
kind: PersistentVolume
metadata:
    annotations:
        volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
    name: my-pv
    namespace: myns
    labels:
        volume-name: my-pv
spec:
    accessModes:
    - ReadWriteOnce
    capacity:
        storage: 2Gi
    csi:
        driver: dobs.csi.digitalocean.com
        fsType: ext4
        #volumeAttributes:
            #volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
        volumeHandle: abc123
    persistentVolumeReclaimPolicy: Retain
    storageClassName: do-block-storage
    volumeMode: Filesystem
