---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: tiller-sa
  namespace: kube-system


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-sa-crb
  namespace: kube-system

subjects:
- kind: ServiceAccount
  name: tiller-sa
  namespace: kube-system

roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-admin