---
kind: Deployment
apiVersion: apps/v1

metadata:
  name: fortune-deployment
  labels:
    app: forutne
    version: v1

spec:
  replicas: 4
  selector:
    matchLabels:
      app: fortune-pod
      version: v1
  template:
    metadata:
      name: fortune-pod
      labels:
        app: fortune-pod
        version: v1

    spec:
      containers:
      - name: fortune
        image: stackupiss/fortune:v1
        imagePullPolicy: Always
        ports:
        - name: app-port
          containerPort: 3000
