---
kind: Deployment
apiVersion: apps/v1

metadata:
   name: mydb-deploy
   namespace: myns
   labels:
      app: mydb-deploy
      version: v1

spec:
   replicas: 1
   selector:
      matchLabels:
         app: mydb-pod
   minReadySeconds: 30
   template:
      metadata:
         name: mydb-pod
         labels:
            app: mydb-pod
            version: v1
      spec:
         containers:
         - name: mydb
           image: stackupiss/northwind-db:v1
           imagePullPolicy: IfNotPresent
           ports:
           - name: mysql-port
             containerPort: 3306
---
kind: Service
apiVersion: v1

metadata:
  name: mydb-svc
  namespace: myns
  labels:
    app: mydb-svc
  
spec:
  type: ClusterIP
  selector:
    app: mydb-pod
  ports:
  - name: mydb-sv-port
    port: 3306
    targetPort: mysql-port
