version: '3'
services:
  app:
    build: ./sever
    ports:
      - "3001:3000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=changeit
      - DB_HOST=db
    networks:
      - mynet
    depends_on:
      - db


db:
  image: stackupiss/northwind-db:v1
  networks: 
    - mynet
  volumes:
    - myvol2:/var/lib/mysql
